env = Environment()

env.Append(
    CCFLAGS=[
        '-Wall', '-Wno-unused-but-set-variable', '-Wno-unused-variable',
        '-g'
#        '-Werror',
    ]
)

env.Program(target='hello', source=['hello.cc'])
env.Program(target='exercises_0', source=['exercises_0.cc'])
#env.Program(target='ex0_5', source=['ex0_5.cc'])
env.Program(target='ex0_6', source=['ex0_6.cc'])

env.Program(target='input', source=['input.cc'])
env.Program(target='framed_greeting', source=['framed_greeting.cc'])
env.Program(target='exercises_1', source=['exercises_1.cc'])
env.Program(target='ex1_4', source=['ex1_4.cc'])
env.Program(target='ex1_5', source=['ex1_5.cc'])


env.Program(target='loop_greeting', source=['loop_greeting.cc'])
env.Program(target='exercises_2', source=['exercises_2.cc'])

env.Program(target='student_grades', source=['student_grades.cc'])
env.Program(target='exercises_3', source=['exercises_3.cc'])


# Ch. 4
env.Program(target='organized_grades_calculator', source=['organized_grades_calculator.cc'])
env.Program(
    target='ch4_data',
    source=['ch4_data.cc', 'student_info.cc', 'grade.cc', 'median.cc']
)
env.Program(target='exercises_4', source=['exercises_4.cc'])

# Ch. 5
env.Program(
    target='ch5_iterators',
    source=['ch5_iterators.cc', 'grade.cc', 'median.cc']
)
env.Program(target='exercises_5', source=['exercises_5.cc'])
env.Program(target='ex5_2', source=['ex5_2.cc', 'student_info.cc', 'grade.cc', 'median.cc'])
env.Program(target='ex5_3', source=['ex5_3.cc', 'student_info.cc', 'grade.cc', 'median.cc'])
env.Program(target='ex5_5', source=['ex5_5.cc'])

# Ch. 6
env.Program(
    target='ch6_algorithms',
    source=['ch6_algorithms.cc', 'student_info.cc', 'grade.cc', 'median.cc', 'util.cc']
)
env.Program(target='exercises_6', source=['exercises_6.cc'])
env.Program(target='ex6_1', source=['ex6_1.cc'])
env.Program(target='ex6_2', source=['ex6_2.cc'])
env.Program(target='ex6_3', source=['ex6_3.cc'])
env.Program(target='ex6_4', source=['ex6_4.cc'])
env.Program(target='ex6_7', source=['ex6_7.cc', 'student_info.cc'])
env.Program(target='ex6_8', source=['ex6_8.cc', 'student_info.cc'])
env.Program(target='ex6_9', source=['ex6_9.cc'])

# Ch. 7
env.Program(
    target='ch7_associative',
    source=['ch7_associative.cc', 'split.cc', 'util.cc', 'characters.cc']
)

# Don't bother trying to cram everything in one file any more.  No point because
# all programs are quite large.
env.Program(target='ex7_1', source=['ex7_1.cc', 'util.cc'])
env.Program(target='ex7_2', source=['ex7_2.cc', 'student_info.cc', 'grade.cc', 'median.cc'])
env.Program(target='ex7_3', source=['ex7_3.cc', 'split.cc', 'characters.cc'])
env.Program(target='ex7_4', source=['ex7_4.cc', 'split.cc', 'characters.cc'])
env.Program(target='ex7_5', source=['ex7_5.cc', 'split.cc', 'util.cc', 'characters.cc'])
env.Program(target='ex7_6', source=['ex7_6.cc', 'split.cc', 'util.cc', 'characters.cc'])
env.Program(target='ex7_7', source=['ex7_7.cc', 'split.cc', 'characters.cc'])
env.Program(target='ex7_8', source=['ex7_8.cc', 'url_finder.cc'])
env.Program(target='ex7_9', source=['ex7_9.cc'])

# Ch 8

env.Program(
    target='ch8_generic',
    source=['ch8_generic.cc', 'util.cc', 'split.cc', 'characters.cc']
)

env.Program(target='ex8_1', source=['ex8_1.cc', 'student_info.cc', 'median.cc', 'grade.cc'])
env.Program(target='ex8_2', source=['ex8_2.cc', 'util.cc'])
env.Program(target='ex8_3', source=['ex8_3.cc', 'util.cc'])
env.Program(target='ex8_4', source=['ex8_4.cc', 'util.cc'])
env.Program(target='ex8_5', source=['ex8_5.cc', 'util.cc', 'split.cc', 'characters.cc', 'random.cc'])
env.Program(target='ex8_6', source=['ex8_6.cc', 'util.cc'])
env.Program(target='ex8_7', source=['ex8_7.cc'])
env.Program(target='ex8_8', source=['ex8_8.cc'])


# Ch 9

env.Program(
    target='ch9_new_types',
    source=['ch9_new_types.cc', 'median.cc']
)

env.Program(target='ex9_1', source=['ex9_1.cc', 'median.cc'])
env.Program(target='ex9_2', source=['ex9_2.cc', 'median.cc'])
env.Program(target='ex9_3', source=['ex9_3.cc', 'median.cc'])
env.Program(target='ex9_4', source=['ex9_4.cc', 'median.cc'])
env.Program(target='ex9_5', source=['ex9_5.cc'])
env.Program(target='ex9_6', source=['ex9_6.cc'])
env.Program(target='ex9_7', source=['ex9_7.cc', 'median.cc'])

# Ch 10

env.Program(
    target='ch10_memory',
    source=['ch10_memory.cc']
)

env.Program(target='ex10_1', source=['ex10_1.cc', 'median.cc'])
env.Program(target='ex10_2', source=['ex10_2.cc'])
env.Program(target='ex10_3', source=['ex10_3.cc', 'util.cc'])
env.Program(target='ex10_4', source=['ex10_4.cc'])
env.Program(target='ex10_5', source=['ex10_5.cc'])
env.Program(target='ex10_6', source=['ex10_6.cc', 'characters.cc'])



env.Program(
    target='ch11_adt',
    source=['ch11_adt.cc']
)

env.Program(target='ex11_1', source=['ex11_1.cc'])
env.Program(target='ex11_2', source=['ex11_2.cc'])
env.Program(target='ex11_3', source=['ex11_3.cc'])
env.Program(target='ex11_4', source=['ex11_4.cc'])
env.Program(target='ex11_5', source=['ex11_5.cc', 'median.cc'])
env.Program(target='ex11_6', source=['ex11_6.cc'])
env.Program(target='ex11_7', source=['ex11_7.cc'])
env.Program(target='ex11_8', source=['ex11_8.cc'])
env.Program(target='ex11_9', source=['ex11_9.cc'])

env.Program(
    target='ch12_class_values',
    source=['ch12_class_values.cc']
)

env.Program(target='ex12_1', source=['ex12_1.cc'])
env.Program(target='ex12_2', source=['ex12_2.cc'])
env.Program(target='ex12_3', source=['ex12_3.cc'])
env.Program(target='ex12_4', source=['ex12_4.cc'])
env.Program(target='ex12_5', source=['ex12_5.cc'])
env.Program(target='ex12_6', source=['ex12_6.cc'])
env.Program(target='ex12_7', source=['ex12_7.cc'])
env.Program(target='ex12_8', source=['ex12_8.cc'])
env.Program(target='ex12_9', source=['ex12_9.cc'])
env.Program(target='ex12_10', source=['ex12_10.cc'])
env.Program(target='ex12_11', source=['ex12_11.cc'])
env.Program(target='ex12_12', source=['ex12_12.cc'])
env.Program(target='ex12_13', source=['ex12_13.cc'])
env.Program(target='ex12_14', source=['ex12_14.cc'])


env.Program(
    target='ch13_inheritance',
    source=['ch13_inheritance.cc', 'median.cc', 'read_hw.cc', 'grading_functions.cc']
)

env.Program(target='ex13_1', source=['ex13_1.cc', 'grading_functions.cc', 'median.cc', 'read_hw.cc'])
env.Program(target='ex13_2', source=['ex13_2.cc', 'median.cc', 'read_hw.cc'])
env.Program(target='ex13_3', source=['ex13_3.cc', 'median.cc', 'grading_functions.cc', 'read_hw.cc'])
env.Program(target='ex13_4', source=['ex13_4.cc', 'median.cc', 'grading_functions.cc', 'read_hw.cc'])
env.Program(target='ex13_5', source=['ex13_5.cc', 'median.cc', 'grading_functions.cc', 'read_hw.cc'])
env.Program(target='ex13_6', source=['ex13_6.cc', 'median.cc', 'grading_functions.cc', 'read_hw.cc'])
env.Program(target='ex13_7', source=['ex13_7.cc'])
env.Program(target='ex13_8', source=['ex13_8.cc'])
env.Program(target='ex13_9', source=['ex13_9.cc'])
