Program(target='hello', source=['hello.cc'])
Program(target='exercises_0', source=['exercises_0.cc'])
#Program(target='ex0_5', source=['ex0_5.cc'])
Program(target='ex0_6', source=['ex0_6.cc'])

Program(target='input', source=['input.cc'])
Program(target='framed_greeting', source=['framed_greeting.cc'])
Program(target='exercises_1', source=['exercises_1.cc'])
Program(target='ex1_4', source=['ex1_4.cc'])
Program(target='ex1_5', source=['ex1_5.cc'])


Program(target='loop_greeting', source=['loop_greeting.cc'])
Program(target='exercises_2', source=['exercises_2.cc'])

Program(target='student_grades', source=['student_grades.cc'])
Program(target='exercises_3', source=['exercises_3.cc'])


# Ch. 4
Program(target='organized_grades_calculator', source=['organized_grades_calculator.cc'])
Program(
    target='ch4_data',
    source=['ch4_data.cc', 'student_info.cc', 'grade.cc', 'median.cc']
)
Program(target='exercises_4', source=['exercises_4.cc'])

# Ch. 5
Program(
    target='ch5_iterators',
    source=['ch5_iterators.cc', 'grade.cc', 'median.cc']
)
Program(target='exercises_5', source=['exercises_5.cc'])
Program(target='ex5_2', source=['ex5_2.cc', 'student_info.cc', 'grade.cc', 'median.cc'])
Program(target='ex5_3', source=['ex5_3.cc', 'student_info.cc', 'grade.cc', 'median.cc'])
