env = Environment()

env.Append(CCFLAGS=['-Wall'])

env.Program(target='hello', source=['hello.cc'])
env.Program(target='exercises_0', source=['exercises_0.cc'])
#env.Program(target='ex0_5', source=['ex0_5.cc'])
env.Program(target='ex0_6', source=['ex0_6.cc'])

env.Program(target='input', source=['input.cc'])
env.Program(target='framed_greeting', source=['framed_greeting.cc'])
env.Program(target='exercises_1', source=['exercises_1.cc'])
env.Program(target='ex1_4', source=['ex1_4.cc'])
env.Program(target='ex1_5', source=['ex1_5.cc'])


env.Program(target='loop_greeting', source=['loop_greeting.cc'])
env.Program(target='exercises_2', source=['exercises_2.cc'])

env.Program(target='student_grades', source=['student_grades.cc'])
env.Program(target='exercises_3', source=['exercises_3.cc'])


# Ch. 4
env.Program(target='organized_grades_calculator', source=['organized_grades_calculator.cc'])
env.Program(
    target='ch4_data',
    source=['ch4_data.cc', 'student_info.cc', 'grade.cc', 'median.cc']
)
env.Program(target='exercises_4', source=['exercises_4.cc'])

# Ch. 5
env.Program(
    target='ch5_iterators',
    source=['ch5_iterators.cc', 'grade.cc', 'median.cc']
)
env.Program(target='exercises_5', source=['exercises_5.cc'])
env.Program(target='ex5_2', source=['ex5_2.cc', 'student_info.cc', 'grade.cc', 'median.cc'])
env.Program(target='ex5_3', source=['ex5_3.cc', 'student_info.cc', 'grade.cc', 'median.cc'])
env.Program(target='ex5_5', source=['ex5_5.cc'])

# Ch. 5
env.Program(
    target='ch6_algorithms',
    source=['ch6_algorithms.cc', 'student_info.cc', 'grade.cc', 'median.cc']
)
env.Program(target='exercises_6', source=['exercises_6.cc'])
env.Program(target='ex6_1', source=['ex6_1.cc'])
env.Program(target='ex6_2', source=['ex6_2.cc'])
env.Program(target='ex6_3', source=['ex6_3.cc'])
